# Generated by Django 3.1.1 on 2022-02-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='photoes/products'),
        ),
        migrations.AlterField(
            model_name='komandalar',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
