# Generated by Django 3.1.1 on 2022-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20220212_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komandalar',
            name='image',
            field=models.ImageField(upload_to='photoes/products'),
        ),
    ]
